name: Release Github Dev Package

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: dist/*
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
